# Generated by Django 5.1.3 on 2024-12-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=75)),
                ('release', models.DateField()),
                ('available', models.BooleanField()),
                ('details', models.TextField(max_length=300)),
            ],
        ),
    ]
