# Generated by Django 5.1.3 on 2024-12-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediathequePython', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='release',
        ),
    ]
