# Generated by Django 5.1.3 on 2024-12-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediathequePython', '0002_remove_media_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
