# Generated by Django 5.1.3 on 2024-12-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediathequePython', '0003_alter_media_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
