# Generated by Django 5.1.4 on 2024-12-16 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('issue', models.DateField()),
                ('dateLoan', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jeux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameTitle', models.CharField(max_length=100, unique=True)),
                ('gameEditor', models.CharField(max_length=100, unique=True)),
                ('numPlayer', models.IntegerField()),
                ('gameDuration', models.IntegerField()),
                ('issue', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CDs',
            fields=[
                ('medias_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logisticMediatheque.medias')),
                ('musicEditor', models.CharField(max_length=100, unique=True)),
                ('artist', models.CharField(max_length=100, unique=True)),
                ('numPist', models.IntegerField()),
            ],
            bases=('logisticMediatheque.medias',),
        ),
        migrations.CreateModel(
            name='DVDs',
            fields=[
                ('medias_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logisticMediatheque.medias')),
                ('studio', models.CharField(max_length=100, unique=True)),
                ('filmDuration', models.IntegerField()),
                ('director', models.CharField(max_length=100, unique=True)),
            ],
            bases=('logisticMediatheque.medias',),
        ),
        migrations.CreateModel(
            name='Livres',
            fields=[
                ('medias_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logisticMediatheque.medias')),
                ('bookEditor', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100, unique=True)),
                ('numPages', models.IntegerField()),
            ],
            bases=('logisticMediatheque.medias',),
        ),
    ]
