# Generated by Django 5.1.4 on 2024-12-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticMediatheque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cds',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cds',
            name='musicEditor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dvds',
            name='director',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dvds',
            name='studio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='gameEditor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='livres',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='livres',
            name='bookEditor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medias',
            name='dateLoan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
