# Generated by Django 5.1.4 on 2024-12-16 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticMediatheque', '0002_alter_cds_artist_alter_cds_musiceditor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupOrSinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='cds',
            name='musicEditor',
        ),
        migrations.RemoveField(
            model_name='dvds',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='livres',
            name='bookEditor',
        ),
        migrations.AlterField(
            model_name='livres',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logisticMediatheque.author'),
        ),
        migrations.AlterField(
            model_name='dvds',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logisticMediatheque.director'),
        ),
        migrations.AddField(
            model_name='livres',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logisticMediatheque.editor'),
        ),
        migrations.AlterField(
            model_name='cds',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logisticMediatheque.grouporsinger'),
        ),
        migrations.AddField(
            model_name='cds',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logisticMediatheque.label'),
        ),
    ]
