# Generated by Django 5.1.4 on 2024-12-16 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticMediatheque', '0003_author_director_editor_grouporsinger_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='jeux',
            name='gameEditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logisticMediatheque.gameeditor'),
        ),
    ]
