# Generated by Django 5.1.4 on 2024-12-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticMediatheque', '0005_author_name_director_name_editor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medias',
            name='mediaType',
            field=models.CharField(choices=[('LIVRE', 'Livre'), ('CD', 'CD'), ('DVD', 'DVD'), ('MEDIA', 'Media')], default='MEDIA', max_length=5),
        ),
    ]
