# Generated by Django 5.1.4 on 2024-12-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticMediatheque', '0006_medias_mediatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeux',
            name='numPlayer',
            field=models.CharField(max_length=10),
        ),
    ]
