# Generated by Django 5.1.4 on 2024-12-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticMediatheque', '0007_alter_jeux_numplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medias',
            name='mediaType',
            field=models.CharField(choices=[('livre', 'Livre'), ('cd', 'CD'), ('dvd', 'DVD')], default='livre', max_length=5),
        ),
    ]
