# Generated by Django 5.1.4 on 2024-12-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticMediatheque', '0009_membres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='canLoan',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='membres',
            name='numLoan',
            field=models.IntegerField(default=0),
        ),
    ]
