# Generated by Django 5.1.4 on 2024-12-19 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticMediatheque', '0010_alter_membres_canloan_alter_membres_numloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='medias',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logisticMediatheque.membres'),
        ),
    ]
