# Generated by Django 5.1.4 on 2024-12-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticMediatheque', '0011_medias_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='Inconnu', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(default='Inconnu', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='editor',
            name='name',
            field=models.CharField(default='Inconnu', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gameeditor',
            name='name',
            field=models.CharField(default='Inconnu', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='grouporsinger',
            name='name',
            field=models.CharField(default='Inconnu', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(default='Inconnu', max_length=100, unique=True),
        ),
    ]
